"use strict";
exports.__esModule = true;
var LinkedList_1 = require("./LinkedList");
// import { Sorter } from "./Sorter";
// const collection = new NumberCollection([10, 3, -5, 0]);
// collection.sort();
// console.log(collection.data);
// const collectionString = new CharacterCollection('cadf');
// collectionString.sort();
// console.log(collectionString.data);
var linkedList = new LinkedList_1.LinkedList();
linkedList.add(500);
linkedList.add(-10);
linkedList.add(-3);
linkedList.add(4);
linkedList.sort();
linkedList.print();
